language: elixir
elixir:
  - 1.3.4
otp_release:
  - 18.3
  - 19.0 
env: MIX_ENV=test
sudo: false # faster builds
notifications:
  email: false
script:
  - mix compile --warnings-as-errors
  - mix test
  - mix credo
