name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master
jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Install Dependencies
        uses: erlef/gh-actions/preview/mix-deps-get@main
        with:
          elixir-version: ${{ steps.beam.outputs.elixir-version }}
          erlang-version: ${{ steps.beam.outputs.otp-version }}

      - name: Update SSL Verify Fun
        run: |
          mix deps.update ssl_verify_fun

      - name: Run Tests
        run: mix test

  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Install Dependencies
        uses: erlef/gh-actions/preview/mix-deps-get@main
        with:
          elixir-version: ${{ steps.beam.outputs.elixir-version }}
          erlang-version: ${{ steps.beam.outputs.otp-version }}

      - name: Run Formatter
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo
